#!/bin/bash
##SBATCH -A cis250092p # 2021 Allocation -- This might change in the following years.
#SBATCH -J particle-mpi16
#SBATCH -o particle-mpi16.stdout
#SBATCH -N 1
#SBATCH -n 1         
#SBATCH -p RM
#SBATCH -t 00:10:00     

source modules.sh

mpirun -n 1 ./mpi -n 1000 -o mpi.txt
